### ISSUE TITLE
Error loading extension with sqlite installed via brew

### ISSUE THREAD

**Issue by andrew8er** [karlb/sqlite-spellfix#3]
I get the following (not very helpful) error when loading this extension with `connection.load_extension(sqlite_spellfix.extension_path())`:

```
  File "/.../database/__init__.py", line 25, in init_sqlite
    connection.load_extension(sqlite_spellfix.extension_path())
sqlite3.OperationalError: error during initialization: 
```

I fixed this by replacing the library file with an updated version compiled from [here](https://github.com/sqlite/sqlite/blob/988af251d86f57e57b77f0bf3e651bab2ff9f343/ext/misc/spellfix.c):

```sh
gcc -g -fPIC -dynamiclib spellfix.c -o spellfix1.cpython-39-darwin.so -I/usr/local/Cellar/sqlite/3.40.1/include
```

**Comment by andrew8er** [comment]
Any chance of fixing this? Is this project actually maintained @karlb?

**Comment by karlb** [comment]
Sorry for the long wait. It is included now and I uploaded a fresh release to PyPI. Let me know if there are any problems with it.

I thought this package might get obsolete when sqlite is included in the sqlean set of extensions (which I package in https://github.com/karlb/sqlite-sqlean), but it didn't happen yet. I can take care of this repo as long as it stays low maintenance, but I'll have to rely on contributions for non-linux builds and debugging. Usually sqlite is pretty low on platform specific issues, though.

**Comment by andrew8er** [comment]
> Sorry for the long wait. It is included now and I uploaded a fresh release to PyPI. Let me know if there are any problems with it.

No problem, thanks for updating the package.

Unfortunately, this is still not working, and I suspect, this is a macOS/brew issue. This package gets compiled with `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/` under macOS, which contains an outdated `sqlite3ext.h` (I'm still on Monterey). It should actually use `/usr/local/opt/sqlite/include` here.

**Comment by karlb** [comment]
I wonder how we could solve this. Neither of these paths is included in a vanilla MacOS, so it might be how the includes are order on your system. Would not like to hard code paths used only by brew (unless they are detected in a reliable way).

Providing precompiled wheels should solve that for most users, but would require actually building them. If anyone writes a github action to create them, I'll upload the result to PyPI. I won't accept prebuilt binaries in a different way since I can neither trust them nor update them.

**Comment by andrew8er** [comment]
Yes, I think this is mostly a `brew` problem, since it's Python packages do not use the system provided sqlite. I'll do some research on this, as soon as I have some time.

**Comment by andrew8er** [comment]
```py
import sysconfig
sysconfig.get_config_vars()['CONFIG_ARGS']
```
reports this string:
```
'--prefix=/usr/local/opt/python@3.11' '--enable-ipv6' '--datarootdir=/usr/local/opt/python@3.11/share' '--datadir=/usr/local/opt/python@3.11/share' '--without-ensurepip' '--enable-loadable-sqlite-extensions' '--with-openssl=/usr/local/opt/openssl@3' '--enable-optimizations' '--with-system-expat' '--with-system-libmpdec' '--with-readline=editline' '--with-lto' '--enable-framework=/usr/local/opt/python@3.11/Frameworks' '--with-dtrace' '--with-dbmliborder=ndbm' 'MACOSX_DEPLOYMENT_TARGET=12' 'CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk' 'CFLAGS_NODIST=-I/usr/local/include' 'LDFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk' 'LDFLAGS_NODIST=-L/usr/local/lib -Wl,-rpath,/usr/local/lib' 'CPPFLAGS=-I/usr/local/include' 'py_cv_module__tkinter=disabled' 'PKG_CONFIG_PATH=/usr/local/opt/mpdecimal/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/12' 'CC=clang'
```

This could be used to detect a `brew` environment. Not very pretty though…
